_target_: src.models.puvae_module.PuVAEModule

classifier_ckpt: "/mnt/apple/k66/ptrang/PuVAE/logs/train/runs/2024-12-18_13-03-55/checkpoints/last.ckpt"

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.cvae.ConditionalVAE
  in_channels: 3
  num_classes: 10
  latent_dim: 10
  img_size: 64
    
classifier:
  _target_: src.models.components.classifier.Classifier
  channels: 3
  image_size: 64

threshold: 0.12
ce_coeff: 10
rc_coeff: 1
kl_coeff: 0.0007
noisy: false
noise_factor: 0.1
  

# compile model for faster training with pytorch 2.0
compile: false
