_target_: src.models.puvae_module.PuVAEModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 20

net:
  _target_: src.models.components.puvae_model.PuVAE
  latent_dim: 32
  channels: 1
  
rc_coeff: 0.01
kl_coeff: 0.1

# compile model for faster training with pytorch 2.0
compile: false
