# @package _global_

defaults:
  - _self_
  - data: mnist # choose datamodule with `test_dataloader()` for evaluation
  - model: puvae_module
  - logger: wandb
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "infer"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: "/mnt/banana/student/ptrang/PuVAE/logs/train/runs/2024-12-18_20-14-58/checkpoints/last.ckpt"

data:
  num_workers: 4

train: False

test:
  attack_eps: 0.3  # Perturbation magnitude for FGSM
  seed: 42

# compile model for faster training with pytorch 2.0
compile: false